CREATE TABLE IF NOT EXISTS CLIENTS (
    ID      INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME    VARCHAR(25) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS EMAILS (
    ID      INTEGER AUTO_INCREMENT PRIMARY KEY,
    EMAIL   VARCHAR(60) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS PHONES (
    ID      INTEGER AUTO_INCREMENT PRIMARY KEY ,
    PHONE   VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS CLIENTS_EMAILS (
    CLIENT_ID      INTEGER NOT NULL,
    EMAIL_ID       INTEGER NOT NULL,
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (ID) ON DELETE CASCADE,
    FOREIGN KEY (EMAIL_ID) REFERENCES EMAILS (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CLIENTS_PHONES (
    CLIENT_ID      INTEGER NOT NULL,
    PHONE_ID       INTEGER NOT NULL,
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (ID) ON DELETE CASCADE,
    FOREIGN KEY (PHONE_ID) REFERENCES PHONES (ID) ON DELETE CASCADE
);

