CREATE TABLE IF NOT EXISTS CLIENTS (
    ID      INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME    VARCHAR(25) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS EMAILS (
    ID          INTEGER AUTO_INCREMENT PRIMARY KEY,
    EMAIL       VARCHAR(60) UNIQUE NOT NULL,
    CLIENT_ID   INTEGER,
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PHONES (
    ID          INTEGER AUTO_INCREMENT PRIMARY KEY ,
    PHONE       VARCHAR(20),
    CLIENT_ID   INTEGER,
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (ID) ON DELETE CASCADE
);


