openapi: 3.0.3
info:
  description: simple_clients_demo API
  title: simple_clients_demo API
  version: 1.0.0
servers:
- url: https://http://localhost:8080
paths:
  /clients/{id}:
    get:
      operationId: getById
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FullClientDto'
          description: OK
      summary: GET clients/{id}
      x-accepts: '*/*'
  /clients:
    get:
      operationId: getUserItems
      responses:
        "200":
          content:
            '*/*':
              schema:
                items:
                  $ref: '#/components/schemas/ClientDto'
                type: array
          description: OK
      summary: GET clients
      x-accepts: '*/*'
    post:
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewClientDto'
        required: true
      responses:
        "201":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ClientDto'
          description: Created
      summary: POST clients
      x-contentType: application/json
      x-accepts: '*/*'
components:
  schemas:
    ContactDto:
      example:
        contact: contact
        contactType: EMAIL
        id: 6
      properties:
        id:
          format: int64
          type: integer
        contact:
          type: string
        contactType:
          enum:
          - EMAIL
          - PHONE
          type: string
      type: object
    FullClientDto:
      example:
        name: name
        id: 0
        contacts:
        - contact: contact
          contactType: EMAIL
          id: 6
        - contact: contact
          contactType: EMAIL
          id: 6
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
        contacts:
          items:
            $ref: '#/components/schemas/ContactDto'
          type: array
      type: object
    ClientDto:
      example:
        name: name
        id: 0
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
      type: object
    NewClientDto:
      example:
        name: name
      properties:
        name:
          type: string
      type: object

